name: Feature request
description: "Are we missing something? Open a feature request and we'll get it implemented!"
labels: feature-request
body:
  - type: textarea
    id: feature_problem
    attributes:
      label: Problem description
      description: 'If your feature request is related to a problem, describe it'
      placeholder: "I'm always frustrated when [...]"
  - type: textarea
    id: feature_description
    attributes:
      label: Feature description
      description: Describe the feature/solution you'd like
    validations:
      required: true
  - type: textarea
    id: feature_alternatives
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered
  - type: textarea
    id: additional_info
    attributes:
      label: Additional information
      description: Add any other context about the feature here.
