name: Build on main/stable push

on:
  push:
    branches: [main, stable]
    tags:
      - '!v*'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      publish-snap: false
    secrets:
      snapcraftIdEdge: ${{ secrets.SNAPCRAFT_ID_EDGE }}
      workflowToken: ${{ secrets.WORKFLOW_TOKEN }}
